Update Release Doc
kubernetes-client/python pull request #1229
Opened 2020-08-06 06:54 UTC by scottilee

Adds more detail to the release doc and removes a redundant release file.

/assign @palnabarun

2020-08-17 16:28 UTC, roycaihw commented
/assign

2020-09-09 21:33 UTC, roycaihw reviewed
One comment. LGTM otherwise

2020-09-09 21:33 UTC, roycaihw commented on devel/release.md
> +Remove the tests directory (ref: https://github.com/kubernetes-client/python/commit/ec9c944f076999543cd2122aff2d86f969d82548).
Could you move this line to the "hot issues" section, and link to the upstream issue https://github.com/OpenAPITools/openapi-generator/issues/5377?

2020-09-15 12:10 UTC, palnabarun requested changes
Looks good to me other than what @roycaihw mentioned.

2020-09-21 20:05 UTC, roycaihw commented
/lgtm
/approve

Thanks!

2020-09-21 20:05 UTC, merged