Corrected Grammar Mistakes in README.md
kubernetes-client/python pull request #1291
Opened 2020-10-19 06:40 UTC by coders-i

I'm making some corrections to README.md file like Capitalization mistakes and some Grammar Mistakes.

2020-10-19 16:55 UTC, yliaog commented
please sign cncf cla

2020-10-22 17:05 UTC, palnabarun requested changes
Please find the requested changes inline.

Also, as @yliaog mentioned, you would need to sign the CLA to get the changes tested and merged.

2020-10-22 17:05 UTC, palnabarun commented on README.md
> +All APIs and Model's documentation can be found at the [Generated client's README file](kubernetes/README.md)
The previous version is actually the correct version. Please revert this.

2020-10-22 17:05 UTC, palnabarun commented on README.md
> +Kubernetes supports [three minor releases](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) at a time. "S
This change modifies the meaning of the sentence. We are consistent with the Kubernetes support policy.

Please revert this as well.

2020-10-26 16:20 UTC, palnabarun commented
/tide merge-method-squash

2020-10-26 16:40 UTC, roycaihw commented
/assign @palnabarun

2020-11-13 16:50 UTC, palnabarun commented
@coders-i -- are you still working on this? If yes, can you please make the suggested changes and sign the Kubernetes CLA? If not, can we close this PR?

2020-11-14 03:36 UTC, coders-i commented
Yes, Please close PR

*Priyanshu Arya*



On Fri, Nov 13, 2020 at 10:20 PM Nabarun Pal <notifications@github.com>
wrote:

> @coders-i <https://github.com/coders-i> -- are you still working on this?
> If yes, can you please make the suggested changes and sign the Kubernetes
> CLA? If not, can we close this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes-client/python/pull/1291#issuecomment-726872541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMU6YFJ2CPIFHOP6HJTWBY3SPVPV7ANCNFSM4SVWOQCQ>
> .
>

2020-11-14 19:52 UTC, yliaog commented
/close

2020-11-14 19:52 UTC, closed without merging